# Az DevOps testing install-services.yml

---
  - name: Basic Playbook
    hosts: all
    become: true

    tasks:
      - name: Install Apache
        apt:
         name: apache2
         state: present
        become: true
        
      - name: Start Apache
        service:
         name: apache2
         state: started
        become: true